const Constants = {
  TWITTER_COMSUMER_KEY: "hHa9BYwPBZU4gbrBqOx5Q4bfK",
  TWITTER_CONSUMER_SECRET: "aIDB4HtzD3cH5h2ARpMYsA4biFZz0xqvwBkbeRLroJgCbT3tKG",
  TWITTER_BEATER_TOKEN: "AAAAAAAAAAAAAAAAAAAAABg0aAEAAAAAHgbv7%2F9PI497r8nWft%2BFFLi6DTc%3DsmVNrl6kYWG84O7ExHmKzUPA3VOd3h4ZtFZNAHpSL9PLDyd11y",

};

export default Constants;